// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {brightwheel} from '../models';
import {main} from '../models';
import {library} from '../models';

export function AuthStatus():Promise<boolean>;

export function CancelDownload():Promise<void>;

export function ChooseFolder():Promise<string>;

export function FetchStudents():Promise<Array<brightwheel.Student>>;

export function GetThumbnail(arg1:string,arg2:number):Promise<string>;

export function IsDemo():Promise<boolean>;

export function Logout():Promise<void>;

export function PreviewMedia(arg1:Array<string>,arg2:string,arg3:string):Promise<Array<main.RemoteMediaItem>>;

export function ScanFolder(arg1:string):Promise<Array<library.File>>;

export function StartDownload(arg1:string,arg2:Array<string>,arg3:string,arg4:string):Promise<void>;

export function StartLogin(arg1:string):Promise<string>;
