// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AuthStatus() {
  return window['go']['main']['App']['AuthStatus']();
}

export function CancelDownload() {
  return window['go']['main']['App']['CancelDownload']();
}

export function ChooseFolder() {
  return window['go']['main']['App']['ChooseFolder']();
}

export function FetchStudents() {
  return window['go']['main']['App']['FetchStudents']();
}

export function GetThumbnail(arg1, arg2) {
  return window['go']['main']['App']['GetThumbnail'](arg1, arg2);
}

export function IsDemo() {
  return window['go']['main']['App']['IsDemo']();
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function PreviewMedia(arg1, arg2, arg3) {
  return window['go']['main']['App']['PreviewMedia'](arg1, arg2, arg3);
}

export function ScanFolder(arg1) {
  return window['go']['main']['App']['ScanFolder'](arg1);
}

export function StartDownload(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartDownload'](arg1, arg2, arg3, arg4);
}

export function StartLogin(arg1) {
  return window['go']['main']['App']['StartLogin'](arg1);
}
